// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRUC8IGL_N_7ty5lJHu9ERxOvaJZ7AP0E',
    appId: '1:455325735038:android:276c3a4b0109031d6be02f',
    messagingSenderId: '455325735038',
    projectId: 'mapit-etackel',
    storageBucket: 'mapit-etackel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6h6COUjJuAS8wIKJndIOen4x1UNqO4gQ',
    appId: '1:455325735038:ios:2da5ad16598ac2c36be02f',
    messagingSenderId: '455325735038',
    projectId: 'mapit-etackel',
    storageBucket: 'mapit-etackel.appspot.com',
    androidClientId: '455325735038-thd43ldnta97i8hg8o7krgpqsub77t7i.apps.googleusercontent.com',
    iosClientId: '455325735038-qgfjdajdgd7re9ou0b673mi1ajkki9t1.apps.googleusercontent.com',
    iosBundleId: 'com.etackel.mapit',
  );

}